CREATE TABLE pedido
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor_total DOUBLE PRECISION,
    situacao    VARCHAR(255),
    fk_cliente  INT                                  NOT NULL,
    fk_endereco INT                                  NOT NULL,
    CONSTRAINT pk_pedido PRIMARY KEY (id)
);

ALTER TABLE pedido
    ADD CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (fk_cliente) REFERENCES cliente (id);

ALTER TABLE pedido
    ADD CONSTRAINT FK_ENDERECO_PEDIDO FOREIGN KEY (fk_endereco) REFERENCES endereco (id);