CREATE TABLE endereco
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logradouro  VARCHAR(255),
    numero      INT,
    complemento VARCHAR(255),
    cidade      VARCHAR(255),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);