CREATE TABLE entrega
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_endereco INT                                  NOT NULL,
    fk_pedido   INT                                  NOT NULL,
    CONSTRAINT pk_entrega PRIMARY KEY (id)
);

ALTER TABLE entrega
    ADD CONSTRAINT uc_entrega_fk_pedido UNIQUE (fk_pedido);

ALTER TABLE entrega
    ADD CONSTRAINT FK_ENDERECO_ENTREGA FOREIGN KEY (fk_endereco) REFERENCES endereco (id);

ALTER TABLE entrega
    ADD CONSTRAINT FK_PEDIDO_ENTREGA FOREIGN KEY (fk_pedido) REFERENCES pedido (id);