CREATE TABLE produto
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    preco     DOUBLE PRECISION,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);