CREATE TABLE produto_pedido
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade INT,
    fk_produto INT                                  NOT NULL,
    fk_pedido  INT                                  NOT NULL,
    CONSTRAINT pk_produto_pedido PRIMARY KEY (id)
);

ALTER TABLE produto_pedido
    ADD CONSTRAINT FK_PEDIDO_PRODUTO_PEDIDO FOREIGN KEY (fk_pedido) REFERENCES pedido (id);

ALTER TABLE produto_pedido
    ADD CONSTRAINT FK_PRODUTO_PRODTO_PEDIDO FOREIGN KEY (fk_produto) REFERENCES produto (id);