CREATE TABLE cliente
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    fk_endereco INT,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_fk_endereco UNIQUE (fk_endereco);

ALTER TABLE cliente
    ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (fk_endereco) REFERENCES endereco (id);